### ISSUE TITLE
Docker cannot be deployed on ARM platform

### ISSUE THREAD

**Issue by Beiluo-Wang** [star-39/moe-sticker-bot#11]
When I ran the docker script on an arm server, 
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`. 

And I tried to add `--platform linux/amd64`, but did not work.

**Comment by Beiluo-Wang** [comment]
I deployed manually, and it works well. It would be better if the docker file built for arm platform is also provided.

**Comment by Beiluo-Wang** [comment]
Problem solved.

**Comment by star-39** [comment]
> I deployed manually, and it works well. It would be better if the docker file built for arm platform is also provided.

Sorry, Github Actions does not support AARCH64 CI yet. However, there seems have a workaround available - through QEMU.

I will investigate later, since my Raspberry Pi was broken!
