### ISSUE TITLE
new mariadb support error

### ISSUE THREAD

**Issue by makusujp** [star-39/moe-sticker-bot#13]
git clone again, up to date.
the following mariadb version
`Server version: 10.6.7-MariaDB-1:10.6.7+maria~focal mariadb.org binary distribution`
ran the mysql_secure_installation only
**also tested on 10.5 failed
however when I use the import sticker command
right after input the URL, then server console pop up this error with bot has no response

`No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "moe-sticker-bot/database.py", line 88, in query_tg_id_by_line_id
    cur = CONN.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'`

I clone once so the USE_DB=0 in database.py, and the HAS_DB=false in main.py for sure

Is something went wrong?

**Comment by makusujp** [comment]
managed this issue, by using the mariadb 10.7 should work.

**Comment by star-39** [comment]
Sorry it was my fault, the code only works with a db.

It's now fixed.

Now mariadb is optional. You can just ignore it.
