### ISSUE TITLE
Could you improve the sorting feature please?

### ISSUE THREAD

**Issue by otakutyrant** [star-39/moe-sticker-bot#19]
Thank you for the project!

It is too tedious to sort stickers step-by-step. How about inputing a string to define the new position of stickers? Like "987654321" means all stickers (there are nine stickers in total) are sorted reversely.

**Comment by star-39** [comment]
Thank you for your advice!

I planned to implement WebApp for sticker management months ago but never got started...

Thank you for saying that need aloud! I am actively working on this right now.

**Comment by star-39** [comment]
My goal is to create a WebApp that shows a image grid of stickers, allowing user to simply drag to re-position stickers along with other features... like emoji edit as well?

**Comment by otakutyrant** [comment]
Excellent. Of course that WebApp design is better.

**Comment by otakutyrant** [comment]
Hey. How is the progress now? I clicked "Change order or emoji" but the web page seems wrong.

![2023-03-13-154536_662x780_scrot](https://user-images.githubusercontent.com/64188229/224638075-f2d3fd3f-08f0-49bd-b740-5e19969f712a.png)

**Comment by star-39** [comment]
Oh sorry~~ The certificate of the website expired days ago..

It’s now fixed, please have a try, thank you!

**Comment by otakutyrant** [comment]
I confirm the fix is done. Good job!
