### ISSUE TITLE
Unable to export using Msb App

### ISSUE THREAD

**Issue by caxerx** [star-39/moe-sticker-bot#20]
I’m trying to export this sticker pack to WhatsApp with Msb App on iOS. But I got 404 error in the app.

Sticker Pack: https://t.me/addstickers/ongeki 

![3800E094-4625-4E63-AFFF-251FF8849B25](https://user-images.githubusercontent.com/9213146/220064011-c00a2e89-1b02-4eee-ab4e-a278f477cd7f.png)

**Comment by star-39** [comment]
I'm so sorry for my late in reply.

The server was misconfigured at that day. It should be fine now.

You can also download the new version of the app, which will show a progress bar now.

I'm also planning to improve the user experience and speed and publish to AppStore.

Thank you!

**Comment by caxerx** [comment]
Thanks for fixing the problem. It works now.
