### ISSUE TITLE
pleae support the full screen animate stickers

### ISSUE THREAD

**Issue by makusujp** [star-39/moe-sticker-bot#9]
currently the bot only identify
`LINE TYPE: line_s`
so the full screen animated stickers are all set to static.

kindly support this type in the bot.

**Comment by star-39** [comment]
Thank you for reporting this type!

Confirmed, I'm working on it now.

**Comment by makusujp** [comment]
Updated to the RC-5 (diff: [d02e0cd](https://github.com/star-39/moe-sticker-bot/commit/d02e0cd9bab29cde5e04abcc69d57753e4ba6ebf))
the id of this [6791](https://t.me/addstickers/line_s_popup_6791_fe53b6_by_moe_sticker_bot) as example that does able to work but it contains static and animated stickers
in this pack it always has static first and animated one next for each sticker

**Comment by makusujp** [comment]
> Well, I intended to do so... The "popup effect" sticker is right after the standard static sticker.
> 
> Please tell me if you've got a better idea!
I personally think that the package should be the same as the website showed much make sense.
and if there's the static one with animated together, maybe bot can give options for this particular type?
like ask user to import static or animated for a pack 
even 3rd option could be set for default for both like you currently have.

**Comment by makusujp** [comment]
pulled to diff [bb0225d](https://github.com/star-39/moe-sticker-bot/commit/bb0225dd850f34a92b0ee113095642ce3905e74c)
 noticed the package bot downloaded with png and webm files.
this is also a good way to filter about processing the static image for PNG extension and the webm for animated package.

and the bot can ask the user option after you process the metadata. from the link if it is the type: `LINE TYPE: line_s_popup`
for options 1: static package 2 animated package(pre-selected) 3 system default
*default set for animated one is because the user sees the package in website is animated.
TG ID will be fine due to even user created above all 3 of them, the ID with already has random strings in it is good one, please keep it up.

**Comment by star-39** [comment]
> pulled to diff [bb0225d](https://github.com/star-39/moe-sticker-bot/commit/bb0225dd850f34a92b0ee113095642ce3905e74c) noticed the package bot downloaded with png and webm files. this is also a good way to filter about processing the static image for PNG extension and the webm for animated package.
> 
> and the bot can ask the user option after you process the metadata. from the link if it is the type: `LINE TYPE: line_s_popup` for options 1: static package 2 animated package(pre-selected) 3 system default *default set for animated one is because the user sees the package in website is animated. TG ID will be fine due to even user created above all 3 of them, the ID with already has random strings in it is good one, please keep it up.

Thank you for your advice! My family were suffering from covid these days so.... sorry for delay.

I will add this option later.

However, some "popups" have a animated background and a static sticker. I dont think separating them is a good idea. Requires further investigation.

Again thank you for testing!

**Comment by makusujp** [comment]
> > pulled to diff [bb0225d](https://github.com/star-39/moe-sticker-bot/commit/bb0225dd850f34a92b0ee113095642ce3905e74c) noticed the package bot downloaded with png and webm files. this is also a good way to filter about processing the static image for PNG extension and the webm for animated package.
> > and the bot can ask the user option after you process the metadata. from the link if it is the type: `LINE TYPE: line_s_popup` for options 1: static package 2 animated package(pre-selected) 3 system default *default set for animated one is because the user sees the package in website is animated. TG ID will be fine due to even user created above all 3 of them, the ID with already has random strings in it is good one, please keep it up.
> 
> Thank you for your advice! My family were suffering from covid these days so.... sorry for delay.
> I will add this option later.

Oh, wish your family get well.
and no hurry, just keep report you the results :) 
cheers up!

> However, some "popups" have a animated background and a static sticker. I dont think separating them is a good idea. Requires further investigation.
> Again thank you for testing!

and about the above mentioned, do you have the ID with and without example?
and i believe the action should still go for the original looks like, to keep people not confusing it with animated AND static together.
and with "animated background", i think it is still the animated sticker itself
you see the animation like complete one when use it, not with the front stage or background idea inside.
so I personally think that should handle like the normal one, see if the affect is the same idea with original usage.

**Comment by star-39** [comment]
Okay! Someone opened a new issue and that example is pretty distinctive.

I working on it now. Your opinion is good - add a option to allow user to choose.

**Comment by makusujp** [comment]
pulled to https://github.com/star-39/moe-sticker-bot/commit/29bb54c2e2d6b7d7f785a641b1fe021f88480a48, your RC-9
I use ID: 14030646 to generate the `LINE TYPE: line_s_eff`
that has no option to select, is it still under working stage?

**Comment by star-39** [comment]
> pulled to [29bb54c](https://github.com/star-39/moe-sticker-bot/commit/29bb54c2e2d6b7d7f785a641b1fe021f88480a48), your RC-9 I use ID: 14030646 to generate the `LINE TYPE: line_s_eff` that has no option to select, is it still under working stage?

Hmm yes, it seems that the sticker in popup sets are similar to normal animated stickers, which means the content of static and animated one are pretty the same. Judging this I decided to keep animated one only.

The option to choose animated or both is still WIP. Current objective is to get the bot run faster!

**Comment by makusujp** [comment]
> Hmm yes, it seems that the sticker in popup sets are similar to normal animated stickers, which means the content of static and animated one are pretty the same. Judging this I decided to keep animated one only.
> 
> The option to choose animated or both is still WIP. Current objective is to get the bot run faster!

just hope you later will make the feature complete.
here i just close this issue now.
